version: '2'
volumes:
  db-data2:
services:
  php:
    container_name: yii2_app
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - .:/var/www/html
    ports:
      - '8000:80'
  db:
    container_name: db_local_yii
    build: ./docker/db
    volumes:
      - db-data2:/var/lib/mysql
    ports:
      - '3306:3306'
  phpmyadmin:
    container_name: phpmyadmin_dev_yii
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - '8002:80'